name: Check Java
on: 
  push:
#  pull_request:
#    paths: ['java/**/*.java']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'java/ruleset.xml'
