name:  Compare Functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ starts_with('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ ends_with('Hello', 'lo') }}
