name: PullRequest Description
on: 
  pull_request
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Edit Pull Request Description
        run: |
        DESCRIPTION=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq .body)
        gh pr edit ${{ github.event.pull_request.number }} --body  "://tickets/${{ github.event.pull_request.number }}
        ---
        ${DESCRIPTION}"