name: Test
on: 
  pull_request:
    paths: ['ruby/**/*.rb']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - run: ruby rubyb/test/*.rb
