name: Test_java
on: 
  pull_request:
    paths: ['java/**/*.java']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: java java/test/*.java
